-- https://github.com/ellisonleao/gruvbox.nvim

local gb = {
	bg0 = "#282828",
	bg1 = "#3c3836",
	bg2 = "#504945",
	bg3 = "#665c54",
	bg4 = "#7c6f64",
	bg0_h = "#1d2021",
	bg0_s = "#32302f",
	fg0 = "#fbf1c7",
	fg1 = "#ebdbb2",
	fg2 = "#d5c4a1",
	fg3 = "#bdae93",
	fg4 = "#a89984",
	bright_red = "#fb4934",
	bright_green = "#b8bb26",
	bright_yellow = "#fabd2f",
	bright_blue = "#83a598",
	bright_purple = "#d3869b",
	bright_aqua = "#8ec07c",
	bright_orange = "#fe8019",
	neutral_red = "#cc241d",
	neutral_green = "#98971a",
	neutral_yellow = "#d79921",
	neutral_blue = "#458588",
	neutral_purple = "#b16286",
	neutral_aqua = "#689d6a",
	neutral_orange = "#d65d0e",
	gray = "#928374",
}

local M = {
	background = "dark",
	colors = {
		bg = gb.bg0,
		fg = gb.fg1,
		float_bg = gb.bg1,
		visual_bg = gb.bg3,
		linenr = gb.bg4,
		status_bg = gb.bg2,
		status_fg = gb.fg1,
		status_a_bg = gb.fg3,
		status_a_fg = gb.bg0,
		status_b_bg = gb.fg4,
		status_b_fg = gb.bg0,
		status_c_bg = gb.gray,
		status_c_fg = gb.bg0,
		search_bg = gb.bright_yellow,
		search_fg = gb.bg0,
		pmenu_bg = gb.bg2,
		pmenu_fg = gb.fg1,
		pmenu_sel_bg = gb.bright_blue,
		pmenu_sel_fg = gb.bg2,
		pmenu_thumb = gb.bg4,
		hint = gb.bright_aqua,
		info = gb.bright_blue,
		warn = gb.bright_yellow,
		error = gb.bright_red,
		-- code
		string = gb.bright_green,
		character = gb.bright_purple,
		number = gb.neutral_purple,
		boolean = gb.neutral_red,
		regex = gb.fg1,
		keyword = gb.bright_red,
		func = gb.neutral_green,
		parameter = gb.fg2,
		class = gb.bright_orange,
		property = gb.neutral_orange,
		variable = gb.neutral_blue,
		constant = gb.bright_blue,
		operator = gb.fg,
		ret = gb.fg4,
		conditional = gb.bright_yellow,
		loop = gb.neutral_orange,
		exception = gb.bright_red,
		include = gb.neutral_aqua,
		define = gb.bright_aqua,
		preproc = gb.bright_aqua,
		macro = gb.bright_aqua,
		type = gb.neutral_yellow,
		bracket = gb.fg1,
		tag = gb.bright_blue,
		tag_attribute = gb.bright_aqua,
		tag_delimiter = gb.fg4,
		comment = gb.gray,
	},
}

return M

