-- https://github.com/ellisonleao/gruvbox.nvim

local gruvbox_dark = {
	bg0 = "#282828",
	bg1 = "#3c3836",
	bg2 = "#504945",
	bg3 = "#665c54",
	bg4 = "#7c6f64",
	fg0 = "#fbf1c7",
	fg1 = "#ebdbb2",
	fg2 = "#d5c4a1",
	fg3 = "#bdae93",
	fg4 = "#a89984",
	gray = "#928374",
	red = "#fb4934",
	green = "#b8bb26",
	yellow = "#fabd2f",
	blue = "#83a598",
	purple = "#d3869b",
	aqua = "#8ec07c",
	orange = "#fe8019",
	neutral_red = "#cc241d",
	neutral_green = "#98971a",
	neutral_yellow = "#d79921",
	neutral_blue = "#458588",
	neutral_purple = "#b16286",
	neutral_aqua = "#689d6a",
}

local c = gruvbox_dark

local groups = {
	BugFg0 = { fg = c.fg0 },
	BugFg1 = { fg = c.fg1 },
	BugFg2 = { fg = c.fg2 },
	BugFg3 = { fg = c.fg3 },
	BugFg4 = { fg = c.fg4 },
	BugBg0 = { fg = c.bg0 },
	BugBg1 = { fg = c.bg1 },
	BugBg2 = { fg = c.bg2 },
	BugBg3 = { fg = c.bg3 },
	BugBg4 = { fg = c.bg4 },
	BugGray = { fg = c.gray },
	BugRed = { fg = c.red },
	BugRedBold = { fg = c.red, bold = true },
	BugGreen = { fg = c.green },
	BugGreenBold = { fg = c.green, bold = true },
	BugYellow = { fg = c.yellow },
	BugYellowBold = { fg = c.yellow, bold = true },
	BugBlue = { fg = c.blue },
	BugBlueBold = { fg = c.blue, bold = true },
	BugPurple = { fg = c.purple },
	BugPurpleBold = { fg = c.purple, bold = true },
	BugAqua = { fg = c.aqua },
	BugAquaBold = { fg = c.aqua, bold = true },
	BugOrange = { fg = c.orange },
	BugOrangeBold = { fg = c.orange, bold = true },
	BugRedSign = { fg = c.red, bg = c.bg1 },
	BugGreenSign = { fg = c.green, bg = c.bg1 },
	BugYellowSign = { fg = c.yellow, bg = c.bg1 },
	BugBlueSign = { fg = c.blue, bg = c.bg1 },
	BugPurpleSign = { fg = c.purple, bg = c.bg1 },
	BugAquaSign = { fg = c.aqua, bg = c.bg1 },
	BugOrangeSign = { fg = c.orange, bg = c.bg1 },
	BugRedUnderline = { undercurl = true, sp = c.red },
	BugGreenUnderline = { undercurl = true, sp = c.green },
	BugYellowUnderline = { undercurl = true, sp = c.yellow },
	BugBlueUnderline = { undercurl = true, sp = c.blue },
	BugPurpleUnderline = { undercurl = true, sp = c.purple },
	BugAquaUnderline = { undercurl = true, sp = c.aqua },
	BugOrangeUnderline = { undercurl = true, sp = c.orange },
	--  :h highlight-default
	ColorColumn = { bg = c.bg1 },
	Conceal = { fg = c.blue },
	Cursor = { reverse = true },
	lCursor = { link = "Cursor" },
	CursorIM = {},
	CursorColumn = { link = "CursorLine" },
	CursorLine = { bg = c.bg1 },
	Directory = { link = "BugGreenBold" },
	DiffAdd = { fg = c.green, bg = c.bg0, reverse = true },
	DiffChange = { fg = c.aqua, bg = c.bg0, reverse = true },
	DiffDelete = { fg = c.red, bg = c.bg0, reverse = true },
	DiffText = { fg = c.yellow, bg = c.bg0, reverse = true },
	EndOfBuffer = {},
	TermCursor = { link = "Cursor" },
	TermCursorNC = {},
	ErrorMsg = { fg = c.red, bold = true },
	WinSeparator = {},
	Folded = { fg = c.gray, bg = c.bg1, italic = true },
	FoldColumn = { fg = c.gray, bg = c.bg1 },
	SignColumn = { bg = c.bg1 },
	IncSearch = { fg = c.orange, bg = c.bg0, reverse = true },
	Substitute = { link = "Search" },
	LineNr = { fg = c.bg4 },
	LineNrAbove = { link = "LineNr" },
	LineNrBelow = { link = "LineNr" },
	CursorLineNr = { fg = c.yellow, bg = c.bg1 },
	CursorLineSign = {},
	CursorLineFold = {},
	MatchParen = { bg = c.bg3, bold = true },
	ModeMsg = { link = "BugYellowBold" },
	MsgArea = {},
	MsgSeparator = {},
	MoreMsg = { link = "BugYellowBold" },
	NonText = { link = "BugBg2" },
	Normal = { fg = c.fg1, bg = c.bg0 },
	NormalFloat = { bg = c.bg1 },
	NormalNC = { link = "Normal" },
	Pmenu = { fg = c.fg1, bg = c.bg2 },
	PmenuSel = { fg = c.bg2, bg = c.blue, bold = true },
	PmenuSbar = { bg = c.bg2 },
	PmenuThumb = { bg = c.bg4 },
	Question = { link = "BugOrangeBold" },
	QuickFixLine = { fg = c.bg0, bg = c.yellow, bold = true },
	Search = { fg = c.yellow, bg = c.bg0, reverse = true },
	SpecialKey = { link = "BugFg4" },
	SpellBad = { link = "BugRedUnderline" },
	SpellCap = { link = "BugBlueUnderline" },
	SpellLocal = { link = "BugAquaUnderline" },
	SpellRare = { link = "BugPurpleUnderline" },
	StatusLine = { fg = c.bg2, bg = c.fg1, reverse = true },
	StatusLineNC = { fg = c.bg1, bg = c.fg4, reverse = true },
	TabLine = { fg = c.fg2, bg = c.bg2 },
	TabLineFill = { fg = c.bg4, bg = c.bg1 },
	TabLineSel = { fg = c.bg0, bg = c.fg3 },
	Title = { link = "BugGreenBold" },
	Visual = { bg = c.bg3 },
	VisualNOS = { link = "Visual" },
	WarningMsg = { link = "BugRedBold" },
	Whitespace = {},
	WildMenu = { fg = c.blue, bg = c.bg2, bold = true },
	WinBar = {}, -- TODO
	WinBarNC = {}, --TODO
	--  :h group-name
	Comment = { fg = c.gray, italic = true },
	Constant = { link = "BugPurple" },
	String = { fg = c.green },
	Character = { link = "BugPurple" },
	Number = { link = "BugPurple" },
	Boolean = { link = "BugPurple" },
	Float = { link = "BugPurple" },
	Identifier = { link = "BugBlue" },
	Function = { link = "BugGreenBold" },
	Statement = { link = "BugRed" },
	Conditional = { link = "BugRed" },
	Repeat = { link = "BugRed" },
	Label = { link = "BugRed" },
	Operator = { fg = c.orange },
	Keyword = { link = "BugRed" },
	Exception = { link = "BugRed" },
	PreProc = { link = "BugAqua" },
	Include = { link = "BugAqua" },
	Define = { link = "BugAqua" },
	Macro = { link = "BugAqua" },
	PreCondit = { link = "BugAqua" },
	Type = { link = "BugYellow" },
	StorageClass = { link = "BugOrange" },
	Structure = { link = "BugAqua" },
	Typedef = { link = "BugYellow" },
	Special = { link = "BugOrange" },
	SpecialChar = {},
	Tag = {},
	Delimiter = {},
	SpecialComment = {},
	Debug = {},
	Underlined = { fg = c.blue, underline = true },
	Ignore = {},
	Error = { fg = c.red, bold = true },
	Todo = { fg = c.fg0, bold = true, italic = true },
	--  :h lsp-highlight
	LspReferenceText = { link = "BugYellowBold" },
	LspReferenceRead = { link = "BugYellowBold" },
	LspReferenceWrite = { link = "BugOrangeBold" },
	LspCodeLens = { link = "BugGray" },
	LspCodeLensSeparator = {},
	LspSignatureActiveParameter = {},
	--  :h hl-DiagnosticError
	DiagnosticError = { link = "BugRed" },
	DiagnosticWarn = { link = "BugYellow" },
	DiagnosticInfo = { link = "BugBlue" },
	DiagnosticHint = { link = "BugAqua" },
	DiagnosticVirtualTextError = { link = "BugRed" },
	DiagnosticVirtualTextWarn = { link = "BugYellow" },
	DiagnosticVirtualTextInfo = { link = "BugBlue" },
	DiagnosticVirtualTextHint = { link = "BugAqua" },
	DiagnosticUnderlineError = { link = "BugRedUnderline" },
	DiagnosticUnderlineWarn = { link = "BugYellowUnderline" },
	DiagnosticUnderlineInfo = { link = "BugBlueUnderline" },
	DiagnosticUnderlineHint = { link = "BugAquaUnderline" },
	DiagnosticFloatingError = { link = "BugRed" },
	DiagnosticFloatingWarn = { link = "BugOrange" },
	DiagnosticFloatingInfo = { link = "BugBlue" },
	DiagnosticFloatingHint = { link = "BugAqua" },
	DiagnosticSignError = { link = "BugRedSign" },
	DiagnosticSignWarn = { link = "BugYellowSign" },
	DiagnosticSignInfo = { link = "BugBlueSign" },
	DiagnosticSignHint = { link = "BugAquaSign" },
}

vim.cmd("hi clear")
vim.g.colors_name = "gruvbox"
vim.o.termguicolors = true
for group, settings in pairs(groups) do
	vim.api.nvim_set_hl(0, group, settings)
end
